name: Issues Handler
on:
  issues:
    types: [opened, edited]
jobs:
    issues-handler:
      runs-on: ubuntu-latest
      steps:
        - name: Output event details
          run: echo "${{ toJson(github.event) }}"
