name: Section 5 - Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: cd ./section-5-demo && npm ci
      - name: Lint code
        run: cd ./section-5-demo && npm run lint
      - name: Test code
        run: cd ./section-5-demo && npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: cd ./section-5-demo && npm ci
      - name: Build website
        run: cd ./section-5-demo && npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            ./section-5-demo/dist
#         this way it is possible to provided multiple paths, else it would be:
#         path: ./section-5-demo/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output Contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
